name: libgoods-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
   - python=3.9
   # If your docs code examples depend on other packages add them here
   - extract_model
   - netcdf4
   - numpy
   - requests
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
   # - sphinx_rtd_theme
   # - ipython
   - jinja2 #<3.1
   - jupyterlab
   - matplotlib-base
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - recommonmark
   - pip
   - pip:
     - docrep<=0.2.7
     - furo
     - nbsphinx>=0.8.7
     - jupyter_client
     # - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
     - model_catalogs
     # the following are required for model_catalogs
     - datetimerange
     - git+https://github.com/intake/intake-xarray.git
     - git+https://github.com/intake/intake.git
     - siphon  # can get from conda-forge but isn't recognized
