name: linting with pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      working-directory: model_catalogs
      with:
        python-version: '3.8'
    - uses: pre-commit/action@v2.0.0
      working-directory: model_catalogs
